const _ = require('lodash')

const kittens = [
  { title: 'Emergency Kittens (@EmrgencyKittens) | Twitter',
    link: 'https://pbs.twimg.com/profile_images/562466745340817408/_nIu8KHX.jpeg' },
  { title: 'UberKittens Delivers Kittens to Play or Stay',
    link: 'https://newsroom.uber.com/wp-content/uploads/2015/10/HQ_uberkittens_blog_960x540_r1v1.jpg' },
  { title: 'How Killing Kittens Could Save The Human Race [Redacted Tonight ...',
    link: 'http://leecamp.net/wp-content/uploads/kitten-3.jpg' },
  { title: 'Kittens - CatTime',
    link: 'http://cdn3-www.cattime.com/assets/uploads/2011/08/best-kitten-names-1.jpg' },
  { title: 'How will I know when my cat is ready to have her kittens ...',
    link: 'https://aos.iacpublishinglabs.com/question/aq/700px-394px/how-will-i-know-when-my-cat-is-ready-to-have-her-kittens_d689f18b-3b25-45a2-8f1d-f07c8ced23b4.jpg?domain=cx.aos.ask.com' },
  { title: 'Emoji Kittens – Tania Hennessy',
    link: 'http://cdn.shopify.com/s/files/1/1025/0131/files/Emoji_Kittens_Tania_Hennessy_doughnut__2016_Tania_Hennessy.jpg?1850443057690319462' },
  { title: 'Caring for Kittens? A Vet Shares Her Tips From Kitten Season 2015',
    link: 'http://s3.amazonaws.com/assets.prod.vetstreet.com/2a/cd/ee484be546418f40cc3cbc194b52/kitten-in-arms-thinkstockphotos-106397271-335lc070915jpg.jpg' },
  { title: 'Interpretation of a dream in which you saw «Kittens»',
    link: 'http://weknowyourdreams.com/images/kittens/kittens-07.jpg' },
  { title: '20+ Of The Cutest Kittens Ever | Bored Panda',
    link: 'http://static.boredpanda.com/blog/wp-content/uploads/2016/08/cute-kittens-69-57b32c431e8a7__605.jpg' },
  { title: '2048 Kittens rule the world',
    link: 'https://cdn1.vox-cdn.com/thumbor/gnJWGHz5ctIUFFI2xBZvieDZxWA=/0x26:640x453/1280x854/cdn0.vox-cdn.com/assets/1275052/kitten_field_jump.jpeg' },
  { title: 'Kittens who look like rabbits - meet the animal pals who are ...',
    link: 'http://i.dailymail.co.uk/i/pix/2016/07/28/22/36A289FF00000578-3713587-image-a-4_1469742595090.jpg' },
  { title: 'Slittens: Kittens And Sloths Together At Last | Bored Panda',
    link: 'http://static.boredpanda.com/blog/wp-content/uploads/2014/10/kittens-sloths-combined-slittens-30.jpg' },
  { title: 'Kitten Food - Feeding for Growth & Development | Royal Canin',
    link: 'https://www.royalcanin.com/~/media/Royal-Canin/Content/persian-kittens.ashx' },
  { title: '1000+ ideas about Kittens on Pinterest | Cats, Cats For Adoption ...',
    link: 'https://s-media-cache-ak0.pinimg.com/736x/e5/0a/a7/e50aa75ca28265b5cc69f92c055e6ee4.jpg' },
  { title: 'Orphaned Kitten Care | petMD',
    link: 'http://www.petmd.com/sites/default/files/what-to-feed-kitten.jpg' },
  { title: 'Animal Planet Live - Kittens',
    link: 'http://static.ddmcdn.com/gif/apl-kittens-siamese-apl-thumbnail.png' },
  { title: '1000+ ideas about Kittens on Pinterest | Cats, Cats For Adoption ...',
    link: 'https://s-media-cache-ak0.pinimg.com/736x/82/6b/3b/826b3b8bff0675704ed5263a139ffd23.jpg' },
  { title: '2048 kittens',
    link: 'http://vignette4.wikia.nocookie.net/happypasta/images/6/6c/Anime-kittens-cats-praying-496315.jpg/revision/latest?cb=20130914024839' },
  { title: 'How To Bottle-Feed Kittens | Petcha',
    link: 'http://d11kavc4axrfgm.cloudfront.net/pet_care/wp-content/uploads/2015/10/19171352/kitten-bottle-feeding-151019.jpg' },
  { title: 'Healthy Paws for Kittens',
    link: 'http://www.southernhillsanimalhospital.com/sites/site-1450/images/kittens.jpg' },
  { title: 'Kittens have their PAWS chopped off by thugs who dumped them in a ...',
    link: 'http://i.dailymail.co.uk/i/pix/2016/02/10/05/3103D2D300000578-0-image-a-12_1455082577519.jpg' },
  { title: 'Cats and Kittens (@catsnkittys) | Twitter',
    link: 'https://pbs.twimg.com/profile_images/469217937862037504/yd3-lohT.jpeg' },
  { title: 'Los Angeles Has a Kitten Problem | L.A. Weekly',
    link: 'http://images1.laweekly.com/imager/u/745xauto/7455437/los-angeles-kittens-adoption-cats-animal-services.jpg' },
  { title: 'Cats & Kittens',
    link: 'http://www.warrenphotographic.co.uk/photography/bigs/08482-Fluffy-ginger-female-kitten.jpg' },
  { title: 'New Hillary Clinton Ad Features Just Kittens - The New Yorker',
    link: 'http://www.newyorker.com/wp-content/uploads/2015/04/Borowitz-New-Hillary-Clinton-Ad-Features-Just-Kittens-1200.jpg' },
  { title: 'Kitten Bowl - See the Cutest Kittens on TV! | Hallmark Channel',
    link: 'http://cdn.crownmediadev.com/dims4/default/845c34e/2147483647/thumbnail/514x320%5E/quality/90/?url=http%3A%2F%2Fbrightcove04.o.brightcove.com%2F3388362517001%2F3388362517001_4741578717001_Hits-and-Tumbles.jpg%3FpubId%3D3388362517001' },
  { title: 'Here\'s how to get cute KITTENS delivered to your home TODAY ...',
    link: 'http://cdn.images.express.co.uk/img/dynamic/128/590x/kittens-615454.jpg' },
  { title: 'Colorful Kittens Pictures, Photos, and Images for Facebook, Tumblr ...',
    link: 'http://www.lovethispic.com/uploaded_images/90725-Colorful-Kittens.jpg' },
  { title: 'Puppies Vs Kittens - Battles - Comic Vine',
    link: 'http://static.comicvine.com/uploads/original/11113/111134695/3891161-6868490335-cats-.jpg' },
  { title: 'Kittens - cat advice - kittens for sale - kittens for adoption',
    link: 'https://www.rspca.org.uk/webContent/staticImages/SectionImages/Buying-a-kitten-banner.jpg' },
  { title: '1000+ ideas about Kittens on Pinterest | Cats, Cats For Adoption ...',
    link: 'https://s-media-cache-ak0.pinimg.com/736x/5e/09/9b/5e099b69a874dea6acfe78afd13e27bc.jpg' },
  { title: 'Kittens Archives - Petfinder',
    link: 'https://www.petfinder.com/wp-content/uploads/2012/11/99225335-caring-for-stray-kittens-632x475.jpg' },
  { title: 'Kitten - Wikipedia',
    link: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Youngkitten.JPG' },
  { title: 'Black Persian KittensUltra Rare Persian Kittens For Sale – (660 ...',
    link: 'http://dollfacepersiankittens.com/wp-content/uploads/2014/03/1f7a7470EDSM.jpg' },
  { title: '1000+ ideas about Munchkin Kitten on Pinterest | Munchkin Cat ...',
    link: 'https://s-media-cache-ak0.pinimg.com/736x/f8/8e/31/f88e3199c76ee90a5c731178750edef4.jpg' },
  { title: '10 Tips for a Happy and Healthy Kitten | petMD',
    link: 'http://www.petmd.com/sites/default/files/happy-healthy-kitten.jpg' },
  { title: 'Uber delivers cute kittens to stressed workers on National Cat Day ...',
    link: 'http://i.telegraph.co.uk/multimedia/archive/02830/cat_2830677b.jpg' },
  { title: 'How to look after a kitten - kitten care',
    link: 'https://www.rspca.org.uk/webContent/staticImages/SectionImages/Taking_care_of_kittens.jpg' },
  { title: '1000+ ideas about Teacup Kitten on Pinterest | Persian Kittens ...',
    link: 'https://s-media-cache-ak0.pinimg.com/736x/22/43/99/224399d670478ad2f7bd38f65029feba.jpg' },
  { title: '1000+ ideas about Black Kittens on Pinterest | Black Cats, Cats ...',
    link: 'https://s-media-cache-ak0.pinimg.com/736x/5b/11/c6/5b11c6b5eabb728c76b652c330ddaf8e.jpg' },
  { title: '20+ Of The Cutest Kittens Ever | Bored Panda',
    link: 'http://static.boredpanda.com/blog/wp-content/uploads/2016/08/cute-kittens-8-57b30aa345790__605.jpg' },
  { title: 'Cute Kittens Compilation 2015 - YouTube',
    link: 'https://i.ytimg.com/vi/6sta6Gkpgcw/maxresdefault.jpg' },
  { title: '3 Ways to Clean Kittens - wikiHow',
    link: 'http://pad1.whstatic.com/images/thumb/9/9d/Clean-Kittens-Step-1.jpg/aid1648699-728px-Clean-Kittens-Step-1.jpg' },
  { title: '1000+ ideas about Kittens on Pinterest | Cats, Kitty and Pets',
    link: 'https://s-media-cache-ak0.pinimg.com/736x/9e/e8/cb/9ee8cbdc84c02f99acd3d6ab698a9e0e.jpg' },
  { title: 'When are kittens ready to leave their mother? | Reference.com',
    link: 'https://aos.iacpublishinglabs.com/question/aq/700px-394px/kittens-ready-leave-mother_36f67690cea253fd.jpg?domain=cx.aos.ask.com' },
  { title: 'The Basics of Having Kittens - Baby kittens tips for you',
    link: 'http://best1x.com/wp-content/uploads/2016/10/Having-Kittens-1.jpg' },
  { title: '40 Cute Kittens Wallpapers',
    link: 'http://doublemesh.com/wp-content/uploads/2013/11/Playful-kittens-3.jpg' },
  { title: 'What the Heck is Kitten Season Anyway?',
    link: 'http://www.pethealthnetwork.com/sites/default/files/what-heck-kitten-season-anyway-156615469.jpg' },
  { title: 'Alert: Fake puppies and kittens for sale online | Action Fraud',
    link: 'http://www.actionfraud.police.uk/sites/default/files/labrador-and-kitten.jpg' },
  { title: 'How old should kittens be before they leave their mother? | Pets4Homes',
    link: 'http://www.pets4homes.co.uk/images/articles/10/large/cat-breeding-helping-your-kittens-to-grow-up-555ef4e57f8d3.jpg' },
  { title: 'How old should kittens be before they leave their mother? | Pets4Homes',
    link: 'http://www.pets4homes.co.uk/images/articles/10/large/cat-breeding-helping-your-kittens-to-grow-up-555ef4e57f8d3.jpg' },
  { title: 'What Is Fading Kitten Syndrome? | Petcha',
    link: 'http://d11kavc4axrfgm.cloudfront.net/pet_care/wp-content/uploads/2015/11/11143310/mother-cat-and-kitten-151111.jpg' },
  { title: 'Luv Kittens Daily (@LuvKittensDaily) | Twitter',
    link: 'https://pbs.twimg.com/profile_images/578073915693494273/Kvm9b-aX.jpeg' },
  { title: 'What do kittens eat? | Reference.com',
    link: 'https://aos.iacpublishinglabs.com/question/6eb791657394cb1a7d2714ef7e215d11/aq/700px-394px/kittens-eat_669b39e28e1b834_C6_RJkxvSHqNGjxRRI4Gqg.jpg?domain=cx.aos.ask.com' },
  { title: 'Two cute tabby kittens on blue background photo - WP36212',
    link: 'http://www.warrenphotographic.co.uk/photography/bigs/36212-Two-cute-tabby-kittens-on-blue-background.jpg' },
  { title: 'Names for Gray Kittens [Slideshow]',
    link: 'http://cf.ltkcdn.net/cats/images/slide/129551-850x565r1-Gray-kitten-5.jpg' },
  { title: 'Sphynx Kittens With White Background Stock Photo, Picture And ...',
    link: 'http://previews.123rf.com/images/svet_lana/svet_lana1010/svet_lana101000006/8143875-Sphynx-kittens-with-white-background-Stock-Photo.jpg' },
  { title: '15 Pictures Of Mama Cats And Kittens For Mother\'s Day - CatTime',
    link: 'http://cdn2-www.cattime.com/assets/uploads/gallery/15-pictures-of-mama-cats-and-kittens-for-mothers-day/06_cats-kittens-mothers-day.jpg' },
  { title: 'Cats & Kittens 15',
    link: 'http://www.warrenphotographic.co.uk/photography/bigs/18736-Five-Maine-Coon-kittens-7-weeks-old-white-background.jpg' },
  { title: 'Cats & Kittens - Kittens only',
    link: 'http://www.warrenphotographic.co.uk/photography/bigs/34243-Ginger-kittens-white-background.jpg' },
  { title: 'Kitten - Wikipedia',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Kitten_in_Rizal_Park,_Manila.jpg/230px-Kitten_in_Rizal_Park,_Manila.jpg' },
  { title: 'How old should kittens be before they leave their mother? | Pets4Homes',
    link: 'http://www.pets4homes.co.uk/images/articles/3448/large/six-health-essentials-that-you-should-monitor-in-your-kittens-first-few-weeks-of-life-56a6114cb4003.jpg' },
  { title: 'Kitten or Cat - Feed Bag Pet SupplyFeed Bag Pet Supply',
    link: 'http://feedbag.wpengine.com/wp-content/uploads/Easter-Kittens-300x300.jpg' },
  { title: '1000+ ideas about Kittens on Pinterest | Cats, Kitty and Pets',
    link: 'https://s-media-cache-ak0.pinimg.com/736x/f3/23/c9/f323c9e00b403151a827b003f0f816ab.jpg' },
  { title: 'Kitten Nursery | Best Friends Animal Society-Los Angeles',
    link: 'http://1402452014-local-prog-la-prod.s3.amazonaws.com/uploads/images/Kitten2.jpg' },
  { title: 'Cute Kittens (@SoCuteKittens) | Twitter',
    link: 'https://pbs.twimg.com/profile_images/600708453389225984/FdzSOzFL.jpg' },
  { title: 'Beautiful And Cool Pictures Of Kittens',
    link: 'http://s3.amazonaws.com/rapgenius/cats-animals-kittens-background.jpg' },
  { title: '20+ Of The Cutest Kittens Ever | Bored Panda',
    link: 'http://static.boredpanda.com/blog/wp-content/uploads/2016/08/cute-kittens-67-57b32a998544a__605.jpg' },
  { title: 'Kitten - Wikipedia',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Aggressive_Mother_Cat.jpg/220px-Aggressive_Mother_Cat.jpg' },
  { title: 'Kittens HD desktop wallpaper : Widescreen : High Definition ...',
    link: 'http://hd.wallpaperswide.com/thumbs/kittens-t2.jpg' }
]

const quokkas = [
  { title: 'Quokka Facts | Quokkas | Australian Marsupials',
    link: 'http://www.animalfactguide.com/wp-content/uploads/2013/08/quokka1.jpg' },
  { title: '1000+ ideas about Quokka on Pinterest | Koalas, Animals and pets ...',
    link: 'https://s-media-cache-ak0.pinimg.com/736x/ba/14/13/ba1413d7b9e2aed10e092260e60a311a.jpg' },
  { title: 'Quokka The Happiest Animal in the World - YouTube',
    link: 'https://i.ytimg.com/vi/178BWFbldCY/hqdefault.jpg' },
  { title: 'Teenager who kicked Quokka fined $2500 for Rottnest Island animal ...',
    link: 'http://www.watoday.com.au/content/dam/images/1/m/j/7/z/9/image.related.articleLeadwide.620x349.glu0ch.png/1450937301877.jpg' },
  { title: '1000+ ideas about Quokka on Pinterest | Koalas, Animals and pets ...',
    link: 'https://s-media-cache-ak0.pinimg.com/736x/12/3e/cd/123ecd770d309ff249ddec851ec86c38.jpg' },
  { title: '1000+ ideas about Quokka on Pinterest | Koalas, Animals and pets ...',
    link: 'https://s-media-cache-ak0.pinimg.com/736x/f4/63/f1/f463f1b65f0c9814b501d71ace635f3d.jpg' },
]

const shibas = [
  { title: 'Shiba Inu Dog Breed Information, Pictures, Characteristics & Facts ...',
    link: 'http://cdn1-www.dogtime.com/assets/uploads/gallery/shiba-inu-dog-breed-picutres/8-side.jpg' },
  { title: 'Shiba Inu Dog Breed Information - American Kennel Club',
    link: 'http://cdn.akc.org/akcdoglovers/ShibaInu_hero.jpg' },
  { title: 'Shiba Inu - Wikipedia',
    link: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Shiba_inu_taiki.jpg/220px-Shiba_inu_taiki.jpg' },
  { title: '10 Funniest Shiba Inu Videos - YouTube',
    link: 'https://i.ytimg.com/vi/g2ag8t7AvX8/maxresdefault.jpg' },
  { title: 'Shiba Inu Dog Breed Information, Pictures, Characteristics & Facts ...',
    link: 'http://cdn3-www.dogtime.com/assets/uploads/gallery/shiba-inu-dog-breed-picutres/6-face.jpg' },
  { title: 'Shiba Inu Dog Breed Information, Pictures, Characteristics & Facts ...',
    link: 'http://cdn1-www.dogtime.com/assets/uploads/gallery/shiba-inu-dog-breed-picutres/7-senior.jpg' },
  { title: 'Shiba Inu Dog Breed Information, Pictures, Characteristics & Facts ...',
    link: 'http://cdn3-www.dogtime.com/assets/uploads/gallery/shiba-inu-dog-breed-picutres/10-profile.jpg' },
  { title: 'Shiba Inu',
    link: 'http://petguide.com.vsassets.com/wp-content/uploads/2013/02/shiba-inu-1.jpg' },
  { title: 'Is Shiba Inu Really the Right Breed for You? | Japan Info',
    link: 'http://jpninfo.com/wp-content/uploads/2015/12/stubborn-shiba.png' },
  { title: 'Shiba Inu - Pictures, Facts, and User Reviews',
    link: 'https://files.graphiq.com/465/media/images/t2/Shiba_Inu_5187042_i0.jpg' }
]

const nyanCats = [
  { title: 'NYAN.CAT!',
    link: 'http://www.nyan.cat/cats/original.gif' },
  { title: 'Nyan Cat - Wikipedia',
    link: 'https://upload.wikimedia.org/wikipedia/en/e/ed/Nyan_cat_250px_frame.PNG' },
  { title: 'Nyan-cat',
    link: 'http://mashable.com/media/ZgkyMDEyLzEyLzA0L2E5L255YW5jYXRzdGFyLmFEbS5qcGcKcAl0aHVtYgkxMjAweDYyNyM/97972a39/59b/nyan-cat-stars-in-ios-adventure-game-video--e6a4e2ba4c.jpg' },
  { title: 'Nyan Cat [original] - YouTube',
    link: 'https://i.ytimg.com/vi/QH2-TGUlwu4/hqdefault.jpg' },
  { title: 'NYAN.CAT!',
    link: 'http://www.nyan.cat/cats/xmas.gif' },
  { title: 'Nyan Cat - 10 HOURS [ BEST SOUND QUALITY ] 4K UHD ULTRA HD - YouTube',
    link: 'https://i.ytimg.com/vi/SkgTxQm9DWM/maxresdefault.jpg' },
  { title: '1000+ images about Nyan Cat on Pinterest | Nyan cat, Google search ...',
    link: 'https://s-media-cache-ak0.pinimg.com/originals/ce/4b/bb/ce4bbbb20810aca291ce76fccbfd5473.jpg' },
  { title: 'NYAN CAT (@nyannyancat) | Twitter',
    link: 'https://pbs.twimg.com/profile_images/2370446440/6e2jwf7ztbr5t1yjq4c5.jpeg' },
  { title: 'DeviantArt: More Like Nyan Cat Gif by KodiakPaws',
    link: 'http://orig14.deviantart.net/2533/f/2011/310/5/a/giant_nyan_cat_by_daieny-d4fc8u1.png' },
  { title: 'Nyan Cat by PRguitarman on DeviantArt',
    link: 'http://img05.deviantart.net/aaee/i/2011/105/c/0/nyan_cat_wallpaper_by_nyakiru-d3e1zfl.png' }
]

module.exports = _.shuffle([...kittens, ...quokkas, ...shibas, ...nyanCats])
